# Generated by Django 5.2.3 on 2025-07-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingoplaceholder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bingo_images/'),
        ),
    ]
