# Generated by Django 5.2.3 on 2025-07-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenable', '0003_movietitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietitle',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
