# Generated by Django 5.2.15 on 2026-06-17 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenable', '0004_alter_movietitle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenablequestion',
            name='description',
            field=models.TextField(blank=True, help_text="Optional note shown under the question — bonus rules, an 'as of' date, etc."),
        ),
        migrations.AddField(
            model_name='tenablequestion',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='The puzzle goes live on this date. Set a future date to pre-write and schedule it.'),
        ),
    ]
