# Generated by Django 5.2.16 on 2026-07-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenable", "0005_tenablequestion_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActorName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="tenablequestion",
            name="question_type",
            field=models.CharField(
                choices=[("movie", "Movie"), ("actor", "Actor")],
                default="movie",
                help_text="Whether the answers to this puzzle are movie titles or actor names — controls which autocomplete list players see.",
                max_length=10,
            ),
        ),
    ]
