# Generated by Django 5.2.16 on 2026-08-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenable", "0006_actorname_tenablequestion_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenableanswer",
            name="clue",
            field=models.CharField(
                blank=True,
                help_text="Optional hint shown under this answer's number until it's found — e.g. the film title, for a 'name the actor' puzzle.",
                max_length=255,
            ),
        ),
    ]
