# Generated by Django 5.2.16 on 2026-08-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenable", "0007_tenableanswer_clue"),
    ]

    operations = [
        migrations.AddField(
            model_name="actorname",
            name="normalized_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="movietitle",
            name="normalized_title",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
