# Generated by Django 5.2.15 on 2026-06-17 16:15

import django.utils.timezone
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to auto-generate from the title.', max_length=220, unique=True)),
                ('headline', models.CharField(blank=True, help_text='Short teaser shown under the title on the homepage feed.', max_length=300)),
                ('tag', models.CharField(blank=True, help_text="Optional category chip, e.g. 'Box office' or 'Genres'.", max_length=60)),
                ('hero_image', models.ImageField(blank=True, help_text='Large image shown on the feed card and at the top of the article.', null=True, upload_to='articles/heroes/')),
                ('body', markdownx.models.MarkdownxField(help_text='Write in Markdown. Drag an image straight into the box to upload it.')),
                ('is_published', models.BooleanField(default=False, help_text='Untick to keep this as a draft (hidden from the site).')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Articles are ordered newest-first by this date.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
