# Generated by Django 5.2.3 on 2025-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='For your own reference/admin; not used in routing.', max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('link_type', models.CharField(choices=[('static', 'Static URL'), ('dynamic_latest', 'Dynamic — link to latest')], default='static', max_length=20)),
                ('static_url', models.CharField(blank=True, help_text='Example: /bingo/ or /higherorlower/', max_length=200, null=True)),
                ('dynamic_url_name', models.CharField(blank=True, help_text="Django URL pattern name that expects a numeric kwarg. Example: 'tenable:play'", max_length=200, null=True)),
                ('dynamic_param_name', models.CharField(blank=True, help_text="The kwarg name for the URL (e.g., 'question_id', 'game_id', or 'pk').", max_length=50, null=True)),
                ('latest_model_label', models.CharField(blank=True, help_text="app_label.ModelName to query for latest, e.g. 'tenable.TenableQuestion'", max_length=100, null=True)),
                ('latest_field_name', models.CharField(default='id', help_text="Field used to determine latest (usually 'id').", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
