# Generated by Django 5.2.15 on 2026-06-20 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Multiple choice only: which option line is correct? 1 = first line, 2 = second line, and so on.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, help_text='Multiple choice only: type the options, ONE PER LINE.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image shown below the question.', null=True, upload_to='quizzes/questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='reveal_answer',
            field=models.TextField(blank=True, help_text='Click-to-reveal only: the answer shown when the button is pressed.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='The question.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='headline',
            field=models.CharField(blank=True, help_text='Short teaser shown under the title on the quizzes feed.', max_length=300),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Image shown on the feed card and at the top of the quiz.', null=True, upload_to='quizzes/heroes/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Untick to keep this as a draft (hidden from the site).'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Quizzes are ordered newest-first by this date.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('mc', 'Multiple choice'), ('reveal', 'Click to reveal')], default='mc', help_text='Multiple choice (click an option, right=green/wrong=red) or click-to-reveal (a button shows the answer).', max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate from the title.', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tag',
            field=models.CharField(blank=True, help_text="Optional category chip, e.g. 'Trivia' or 'Hard mode'.", max_length=60),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
