# Generated by Django 5.2.3 on 2025-07-18 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('tile_type', models.CharField(choices=[('actor', 'Actor'), ('movie', 'Movie')], max_length=6)),
                ('column', models.PositiveSmallIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='networks.board')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='networks.board')),
                ('from_tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_links', to='networks.tile')),
                ('to_tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_links', to='networks.tile')),
            ],
        ),
    ]
