# Generated by Django 5.2.3 on 2025-07-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
    ]
