# Generated by Django 5.2.15 on 2026-06-17 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_remove_tile_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='The board goes live on this date. Set a future date to pre-make and schedule it.'),
        ),
    ]
