# Generated by Django 5.2.3 on 2025-07-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('box_office', models.PositiveBigIntegerField()),
                ('acting_credits', models.PositiveIntegerField()),
                ('oscar_nominations', models.PositiveIntegerField()),
            ],
        ),
    ]
