# Generated by Django 5.2.3 on 2025-07-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higherorlower', '0002_actor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image_attribution',
            field=models.CharField(blank=True, help_text="Photo credit (e.g., 'Photo by John Smith on Unsplash')", max_length=200, null=True),
        ),
    ]
