# Generated by Django 5.2.3 on 2025-08-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higherorlower', '0003_actor_image_attribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='acting_credits',
            new_name='leading_roles',
        ),
    ]
